# ------------------------------------------------------------------------------
# RIN/PMI and gene count correlation analysis
# Author: Jiahe Tian
# Date: 8/13/2024
# Purpose: It examines the common genes among the sheets generated by corr_each_gene.R
# and produces txt files of those genes for ontology analysis in Enrichr
# ------------------------------------------------------------------------------
# Input:
#   - Have to run corr_each_gene.R first, this script will analysis the generated sheets
# Output:
#   - txt files
# ------------------------------------------------------------------------------

library(dplyr)

# please specify your working directory
setwd("D:/Jiahe/Columbia")

# filter to only keep significant genes that pass the FDR 0.05
sig_RIN_NPH <- read.csv("rna_quality_paper/correlation_on_each_gene (supp 1&2)/NPH_all_gene_RIN_corr.csv") |>
  filter(p.adj < 0.05)
sig_RIN_BB <- read.csv("rna_quality_paper/correlation_on_each_gene (supp 1&2)/BB_all_gene_RIN_corr.csv") |>
  filter(p.adj < 0.05)
sig_PMI_BB <- read.csv("rna_quality_paper/correlation_on_each_gene (supp 1&2)/BB_all_gene_PMI_corr.csv") |>
  filter(p.adj < 0.05)

# note that sig_RIN_ROSMAP just means the oligo dT samples
sig_RIN_ROSMAP <- read.csv("rna_quality_paper/correlation_on_each_gene (supp 1&2)/ROSMAP_oligo_gene_RIN_corr.csv") |>
  filter(p.adj < 0.05)
sig_PMI_ROSMAP <- read.csv("rna_quality_paper/correlation_on_each_gene (supp 1&2)/ROSMAP_oligo_gene_PMI_corr.csv") |>
  filter(p.adj < 0.05)

# sig_RIN_ROSMAP_other means riboDepletion samples
sig_RIN_ROSMAP_other <- read.csv("rna_quality_paper/correlation_on_each_gene (supp 1&2)/ROSMAP_riboDep_gene_RIN_corr.csv") |>
  filter(p.adj < 0.05)
sig_PMI_ROSMAP_other <- read.csv("rna_quality_paper/correlation_on_each_gene (supp 1&2)/ROSMAP_riboDep_gene_PMI_corr.csv") |>
  filter(p.adj < 0.05)

#cleaning
names(sig_RIN_NPH)[1] <- "gene"
names(sig_RIN_BB)[1] <- "gene"
names(sig_PMI_BB)[1] <- "gene"
names(sig_RIN_ROSMAP)[1] <- "gene"
names(sig_PMI_ROSMAP)[1] <- "gene"
names(sig_RIN_ROSMAP_other)[1] <- "gene"
names(sig_PMI_ROSMAP_other)[1] <- "gene"

# common positive correlating genes in RIN
positive_RIN_NPH <- sig_RIN_NPH |>
  filter(RIN > 0)

positive_RIN_BB <- sig_RIN_BB |>
  filter(RIN > 0)

positive_RIN_ROSMAP <- sig_RIN_ROSMAP |>
  filter(RIN > 0)
positive_RIN_ROSMAP_other <- sig_RIN_ROSMAP_other |>
  filter(RIN > 0)

common_genes_RIN <- Reduce(intersect, list(positive_RIN_NPH$gene, positive_RIN_BB$gene, positive_RIN_ROSMAP$gene, positive_RIN_ROSMAP_other$gene))
common_gene_RIN_NPH_ROSMAP <- Reduce(intersect, list(positive_RIN_NPH$gene, positive_RIN_ROSMAP$gene))
common_gene_RIN_NPH_BB <- Reduce(intersect, list(positive_RIN_NPH$gene, positive_RIN_BB$gene))
common_gene_RIN_BB_ROSMAP <- Reduce(intersect, list(positive_RIN_BB$gene, positive_RIN_ROSMAP$gene))

# common negative correlating genes in RIN
neg_RIN_NPH <- sig_RIN_NPH |>
  filter(RIN < 0)

neg_RIN_BB <- sig_RIN_BB |>
  filter(RIN < 0)

neg_RIN_ROSMAP <- sig_RIN_ROSMAP |>
  filter(RIN < 0)
neg_RIN_ROSMAP_other <- sig_RIN_ROSMAP_other |>
  filter(RIN < 0)

common_genes_RIN_neg <- Reduce(intersect, list(neg_RIN_NPH$gene, neg_RIN_BB$gene, neg_RIN_ROSMAP$gene, neg_RIN_ROSMAP_other$gene))
common_gene_RIN_NPH_ROSMAP_neg <- Reduce(intersect, list(neg_RIN_NPH$gene, neg_RIN_ROSMAP$gene))
common_gene_RIN_NPH_BB_neg <- Reduce(intersect, list(neg_RIN_NPH$gene, neg_RIN_BB$gene))
common_gene_RIN_BB_ROSMAP_neg <- Reduce(intersect, list(neg_RIN_BB$gene, neg_RIN_ROSMAP$gene))

# common positive correlating genes in PMI
positive_PMI_BB <- sig_PMI_BB |>
  filter(PMI > 0)

positive_PMI_ROSMAP <- sig_PMI_ROSMAP |>
  filter(PMI > 0)

positive_PMI_ROSMAP_other <- sig_PMI_ROSMAP_other |>
  filter(PMI > 0)

common_genes_PMI <- Reduce(intersect, list(positive_PMI_BB$gene, positive_PMI_ROSMAP$gene, positive_PMI_ROSMAP_other$gene))

# common negative correlating genes in PMI
neg_PMI_BB <- sig_PMI_BB |>
  filter(PMI < 0)

neg_PMI_ROSMAP <- sig_PMI_ROSMAP |>
  filter(PMI < 0)

neg_PMI_ROSMAP_other <- sig_PMI_ROSMAP_other |>
  filter(PMI > 0)

common_genes_PMI_neg <- Reduce(intersect, list(neg_PMI_BB$gene, neg_PMI_ROSMAP$gene, neg_PMI_ROSMAP_other$gene))

# The text files of genes that need for ontology analysis

# genes that has a significant positive correlation with RIN among all 4 sets
file_path <- "rna_quality_paper/correlation_on_each_gene (supp 1&2)/common_pos_genes_RIN.txt"
writeLines(common_genes_RIN, file_path)

# genes that has a significant negative correlation with RIN among all 4 sets
file_path <- "rna_quality_paper/correlation_on_each_gene (supp 1&2)/common_neg_genes_RIN.txt"
writeLines(common_genes_RIN_neg, file_path)

# genes that has a significant positive correlation with PMI among all 3 sets, excluding NPH
file_path <- "rna_quality_paper/correlation_on_each_gene (supp 1&2)/common_pos_genes_PMI.txt"
writeLines(common_genes_PMI, file_path)

# genes that has a significant negative correlation with PMI among all 3 sets, excluding NPH
file_path <- "rna_quality_paper/correlation_on_each_gene (supp 1&2)/common_neg_genes_PMI.txt"
writeLines(common_genes_PMI_neg, file_path)
# 
# # combined table
# sig_RIN_NPH_filtered <- sig_RIN_NPH %>% filter(gene %in% common_genes_RIN) |>
#   rename(RIN_NPH = RIN)
# sig_RIN_BB_filtered <- sig_RIN_BB %>% filter(gene %in% common_genes_RIN) |>
#   rename(RIN_BB = RIN)
# sig_RIN_ROSMAP_filtered <- sig_RIN_ROSMAP %>% filter(gene %in% common_genes_RIN) |>
#   rename(RIN_ROSMAP = RIN)
# 
# # Combine the filtered dataframes by $gene
# common_RIN_df <- sig_RIN_NPH_filtered %>%
#   inner_join(sig_RIN_BB_filtered, by = "gene") %>%
#   inner_join(sig_RIN_ROSMAP_filtered, by = "gene")
# write.csv(common_RIN_df, "rna_quality_paper/correlation_on_each_gene (supp 1&2)/common_rin.csv")
